### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by joshday** [OpenMendel/MendelGWAS.jl#3]
A few ideas for general code/style cleanup.  Feel free to disregard, but these are things I noticed.
- It's arbitrary, but the Julia community uses 4 spaces for indenting.  
- Use `import Module` or `import Module: function1, function2` rather than `using` inside modules.  If someone is trying to find a definition, they need to search through the dependencies to find it.  This tell them where it is.
- It seems the GWAS function changes the users working directory.  This is something that should definitely be fixed.
- Upper case is usually reserved for types/constructors (GWAS -> gwas)

**Comment by Hua-Zhou** [comment]
Better to discuss this under [OpenMendel/CodingStyle](https://github.com/OpenMendel/CodingStyle)?

**Comment by joshday** [comment]
Ah, right.  I'll close this and reopen there.
